### ISSUE TITLE
Upload multiple license keys to one product via REST

### ISSUE THREAD

**Issue by Bexa2** [drazenbebic/license-manager-for-woocommerce#127]
Just like you can load 100 license keys to one product in 1 or 2 seconds using the import page it'd be nice to upload license keys via REST API without having to go 1 by 1.

**Comment by drazenbebic** [comment]
Hello @Bexa2 

makes sense, but I think this will be a new route because I don't want to break compatibility with existing integrations. What would it be called though?

POST - /v2/licenses/**batch** ?

It would probably also make sense to limit the amount of licenses you can add via this route. Either that, or they get automatically separated into batches which will be worked off by WP-CRON.

Any ideas/suggestion?

**Comment by drazenbebic** [comment]
I don't think that this is something the plugin urgently needs, at least not now.
