### ISSUE TITLE
Use as Composer package

### ISSUE THREAD

**Issue by vasikgreif** [drazenbebic/license-manager-for-woocommerce#157]
Hi,
thanks for great plugin! Is there a way to use it as Composer package instead of having to activate the plugin?

**Comment by drazenbebic** [comment]
Hello @vasikgreif 

I would need to prepare and submit my git repo as a PHP package to composer. You can specify PHP packages which aren't part of the composer ecosystem by editing your composer.json, take a look here:

https://barryvanveen.nl/blog/55-installing-a-private-package-with-composer

I'll update the composer.json to include more info like name, author, version, etc, so that you can actually use it that way.

**Comment by vasikgreif** [comment]
Hi @drazenbebic, thanks! Would you please create a feature request for this, so you won't forget this?..:)

**Comment by drazenbebic** [comment]
@vasikgreif 

already done in 4a59442b18a510eb6731765ae6dea09c1652f2b6

Will be included in the next release coming soon.

**Comment by vasikgreif** [comment]
Very cool, thanks!
