### ISSUE TITLE
Question: How to translate the "Your license key(s)" heading in roder confirmations and emails?

### ISSUE THREAD

**Issue by alex-drocks** [drazenbebic/license-manager-for-woocommerce#163]
Hello Drazen!

How could I translate the "**Your license key(s)**" heading text in order confirmation page and email message?
Please see image bellow for reference:
https://i.imgur.com/t8Xvlif.png

In the source code I think I found a place between a `<h2>` tag that references $heading but I don't know where heading is defined and how to properly translate that `<h2>`  to french.

Can you please give me a clue, thanks a lot in advance.
Alexandre Desroches

**Comment by kuserich** [comment]
Hi Alex,

These translations (with a `__` function call) are handled by the WordPress translation catalogue files. Please consult the official [WordPress Localization documentation](https://developer.wordpress.org/plugins/internationalization/localization/) for details on how this works, if you are not yet familiar with them.

For every well-maintained theme and plugin, you will find the official translation files on [translate.wordpress.org](https://translate.wordpress.org/). Similarly, there are a number of translations publicly available in the [translation repository for this plugin ](https://translate.wordpress.org/projects/wp-plugins/license-manager-for-woocommerce/).

From your screenshot, I assume that you are seeking to translate the string you mentioned (and perhaps additional content) into French. There is a French catalogue file readily available in the translation repository for this plugin. You should be able to simply download these and add them to your WordPress installation. These files are installed (copied to) `WORDPRESS_ROOT/wp-content/languages/plugins/`.

In order to be recognized properly, these files must match the name of the plugin that you are targeting as well as the locale that you are using. In your case, this should be `license-manager-for-woocommerce-fr_FR.po` and `license-manager-for-woocommerce-fr_FR.mo`. Such that you will have two files in your languages directory:

```
WORDPRESS_ROOT/wp-content/languages/plugins/license-manager-for-woocommerce-fr_FR.po
WORDPRESS_ROOT/wp-content/languages/plugins/license-manager-for-woocommerce-fr_FR.mo
```

Please note that the language file(s) that you can download do not include the `.mo` file and you will not be able to edit these files directly in, say, a text editor. I recommend using [Poedit](https://poedit.net/) to edit and update these files.
You will also be able to obtain the `.mo` file by simply opening and saving the `.po` file in Poedit.

Summary:
1) Download language files in French from the [translation repository ](https://translate.wordpress.org/projects/wp-plugins/license-manager-for-woocommerce/)
2) Install & open the `.po` language file in Poedit
3) Search for and update the strings you wish to edit
4) Save the file (this will also create the `.mo` file)
5) Copy the files to the server. Make sure to place them in the correct directory and make sure that the naming is correct (plugin name + locale)

**Comment by alex-drocks** [comment]
@kuserich Wow that was a very well written explanation!
Thank you very much. I admit that I was stranger to the whole concept of how Wordpress translates plugins. Your post will get me started well.

**Comment by kuserich** [comment]
Glad to hear that my explanation was helpful to you, @alex-drocks.

I would like to extend my explanation and highlight that the locale that is used in the file names must match the locale (language) that is configured in the WordPress general settings. It may be that my assumption that you are using `fr_FR` is incorrect - or for anyone reading this that's using a different language. You can find name of the locale that is configured in the WordPress admin area under Tools > Site Health > Info in the WordPress tab in the `Site Language` row.

**Comment by alex-drocks** [comment]
@kuserich Yeah, I kind of figured it out yesterday with the info you had given me already but you make it clearer now, In fact I am setup with the canadian french language so `Site Language | fr_CA`.

I found that there is only the french version named like so when I downloaded it: "wp-plugins-license-manager-for-woocommerce-stable-fr.mo" (and the .po also).

The only thing I am wondering, and I haven't test it yet, is if I could just rename the files manually to fr_CA so that it works even if its not technically a canadian french translation?

**Comment by kuserich** [comment]
Yes, that is correct. You can just rename the file manually to `license-manager-for-woocommerce-fr_CA.po`. There is no language detection or anything of that sort. WordPress will only check if there is a file that follows this naming scheme.
