### ISSUE TITLE
Toggleable encryption to database

### ISSUE THREAD

**Issue by srcmkr** [drazenbebic/license-manager-for-woocommerce#32]
It would be nice to disable the encryption and store the unencrypted keys in the database (for direct read/write-access from other services).

**Comment by drazenbebic** [comment]
Hello @srcmkr,

This is something that I originally thought I would implement at launch, but turned out to be a rather difficult feature.

Every time you toggle the encryption, all of your license keys inside the database would have to be either encrypted or decrypted. This would have to be a batch process, especially when you consider installations with a really large number of license keys. While the batch process is running, you would have to disable the toggle, to prevent a potentially corrupted state. If anything goes wrong during the batch processing... I don't know. Haven't thought that far ahead.

I'm open to input and ideas, but as it is now, this is not something I would want to work on. If you really need the encryption/decryption feature, I would much rather add it to the API functionality (i.e. `encrypt` and `decrypt` routes).

Let me know what you think.

**Comment by srcmkr** [comment]
Oh, well - I get your thoughts and the difficulties linked with this issue.
If the keys are going to be encrypted (or not) is a basic architectural decision for sure: Maybe it would be the easiest way to require an empty table to toggle the encryption.

My current workaround is 
```
public function encrypt($value)
{
    return $value;
}
```
and of course the decrypt function :)))

**Comment by drazenbebic** [comment]
Hello @srcmkr,

You are right, it is what it is now. I won't be changing it.

However, I think you're onto something. I will add a "How-To" to the plugin docs on how to use it based on the function you provided. 

All encryption/decryption is done via those two methods, and they are **ALWAYS** called via filters. If you add your own filters which just return the given value, then it should be possible to entirely bypass/disable the encryption.

I would highly discourage anyone to do this, unless they know what they're doing. But I will add it to the documentation as a possibility.

Thanks for the valuable feedback!
